config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  scope path:'/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
  resources :topics
  end

    root "topics#index"
  get '/test',to: "topics#test"

  namespace :admin do
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :users do
    collection do
      get :profile
      put :edit_profile
      get :post_topics
      get :post_comments
      get :like_topics
      get :stored_topics

    end
  end

  resources :categories

  resources :topics do
    collection do
      get :about
      get :last_time
      get :comment_count

    end

    member do
      post :like
      post :unlike
      post :comment
      post :del_comment
      post :store
      post :unstore

    end

  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :topic_categoryships
  has_many :categories, through: :topic_categoryships
  has_one :photo, dependent: :destroy
  accepts_nested_attributes_for :photo
  has_many :store_topicships
  has_many :stored_users, through: :store_topicships, source: :user
  # has_one :topicphoto
  # accepts_nested_attributes_for :topicphoto

  def find_like(user)
    Like.where(topic_id: self.id, user_id: user.id).first
    # Like.where(topic_id: id, user_id: user.id) #也可以

  end

  def is_like_by(user)
    find_like(user).present?
  end
end

app/controllers/api_v1/topics_controller.rb
class ApiV1::TopicsController <  ApiController

  # GET http://localhost:3000/api/v1/topics.json
  def index
    @topics = Topic.all

    @header = request.headers.to_h["HTTP_TEST"]
    # render json: @topics.to_json
    
    #測試header
    # render json: {message: "#{@header}"}
  end

  #GET http://localhost:3000/api/v1/topics/21.json
  def show
    @topic = Topic.find_by_id(params[:id])
    if @topic
      # render json: @topic.to_json
    else
      render json: {message: "failed!!"}, status: 400
    end
  end

  #POST http://localhost:3000/api/v1/topics/21.json
  def create
    @topic = Topic.new(name: params[:name])
    if @topic.save
      render json: {message: "OK!!"}
    else
      render json: { message: "failed!!"}, status: 400
    end
  end

  def update
    @topic = Topic.find_by(id: params[:id])
    if @topic.update(name: params[:name])
      render json: {message: "Update Success!!"}
    else
      render json: { message: "failed!!!"}, status: 400
    end
  end

  def destroy
    @topic = Topic.find_by(id: params[:id])
    if @topic.destroy
      render json: {message: "Success delete!!"}
    else
      render json: {message: "failed!!!"}, status: 400
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    category = Category.find_by(title: params[:category]) if params[:category]

    if params[:new] == "time"
      @topics = Topic.order("created_at DESC").paginate(page: params[:page], per_page: 5)
      # @topics =Topic.includes(:comments).select('id','name','created_at','last_time').order("created_at DESC")
    elsif params[:new]
      sort_by = (params[:new] == "name") ? "name" : "id"

      @topics = Topic.order(sort_by).paginate(page: params[:page], per_page: 5)
    elsif params[:last] == "time"
      @topics = Topic.order("last_time DESC").paginate(page: params[:page], per_page: 5)
    elsif params[:max] == "count"
      @topics = Topic.order("comments_count DESC").paginate(page: params[:page], per_page: 5)
    elsif category
      @topics = category.members.order("created_at DESC").paginate(page: params[:page], per_page: 5)
    elsif params[:view]
      @topics = Topic.order("viewcount DESC").paginate(page: params[:page],per_page: 5)
    else
      @topics = Topic.paginate(page: params[:page], per_page: 5)
    end


  end

  def new
    @topic = Topic.new
    @photo = @topic.build_photo
  end

  def create
    # @topic = Topic.new(topic_params)
    # @topic.user = current_user
    @topic = current_user.topics.new(topic_params)
    find_id = params["topic"]["category_ids"]

    if @topic.save
      
      find_id.each do |id|
        if id.present?
          updatecount = Category.find(id).count += 1
          Category.find(id).update(count: updatecount)
        end

      end
      flash[:notice] = "Success create!!"
      redirect_to topics_path
    else
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @viewcount = @topic.viewcount
    @viewcount += 1
    @topic.update(viewcount: @viewcount)
    @comment_member = @topic.comments.pluck(:user_id).uniq
    @comments = @topic.comments
    if params[:comment_id]
      @comment = Comment.find(params[:comment_id])
      if @comment.photo.present?
        @photo = @comment.photo
      else
        @photo = @comment.build_photo
      end
    else
      @comment = @topic.comments.new
      @photo = @comment.build_photo
    end


  end

  def comment
    if params[:comment_id]
      @topic = Topic.find(params[:id])
      @comment = Comment.find(params[:comment_id])
      @comment.update(comment_params)
      redirect_to topic_path(@topic)
    else
      @topic = Topic.find(params[:id])
      @comment = @topic.comments.new(comment_params)
      @comment.user = current_user
      if @comment.save
        @topic.last_time = @comment.created_at
        @topic.save
        redirect_to topic_path(@topic)
      end
    end

  end

  def del_comment
    @topic = Topic.find(params[:id])
    @comment = Comment.find(params[:comment_id])
    if current_user == @comment.user
      @comment.destroy
      redirect_to topic_path(@topic)
    else
      flash[:warning] = "U don't have permission"
      render :show
    end

  end

  def edit
    @topic = Topic.find(params[:id])

    if @topic.photo.present?
      @photo = @topic.photo
    else
      @photo = @topic.build_photo
    end
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:notice] = "Success to Edit!"
      redirect_to topics_path
    else
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    respond_to do |format|
      #:remote => true
      format.html
      format.js #destroy.js.erb
      # format.js { render text: "alert('you!')" }
    end
    # if @topic.destroy
    #   redirect_to topics_path
    # else
    #   render :index
    # end
  end

  def about

  end

  def like
    @topic = Topic.find(params[:id])
    # byebug
    unless @topic.is_like_by(current_user)
      Like.create(topic: @topic, user: current_user)

      # redirect_to topics_path(page: params[:page])
      # redirect_to :back
    end

    respond_to do |format|
      format.html { redirect_to :back}
      format.js
    end
  end

  def unlike
    @topic = Topic.find(params[:id])
    like = @topic.find_like(current_user)
    like.destroy
    # redirect_to :back

    respond_to do |format|
      format.html {redirect_to :back}
      format.js { render "like"} #like.js.erb
      # format.json { render json: @resource }
    end

  end

  def store
    @topic = Topic.find(params[:id])
    if !current_user.is_store_of?(@topic)
      current_user.store!(@topic)
      flash[:notice] = "收藏成功！！"
    else
      flash[:alert] = "U already store!!"
    end
    redirect_to topic_path(@topic)
  end

  def unstore
    @topic = Topic.find(params[:id])
    if current_user.is_store_of?(@topic)
      current_user.unstore!(@topic)
      flash[:warning] = "已取消收藏！！"
    else
      flash[:alert] = "無法取消！！"
    end
    if params[:topic]
      redirect_to :back
    else
      redirect_to topic_path(@topic)
    end
  end



  private

  def comment_params
    params.require(:comment).permit(:content, photo_attributes: [:image, :id])
  end

  def topic_params
    params.require(:topic).permit(:name, :date, :description, category_ids: [], photo_attributes: [:id, :image])
  end
end

app/helpers/api_v1/topics_helper.rb
module ApiV1::TopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_like.html.erb
<% topic.liked_users.each do |user| %>
  <%= user.display_name %>
<% end %>

app/views/topics/_likebutton.html.erb
<% if current_user && topic.is_like_by(current_user) %>
  <%= link_to "-1", unlike_topic_path(topic, page: params[:page]), :method => :post, :class => "btn btn-primary", :remote => true %>
<% else %>
   <%= link_to "+1", like_topic_path(topic, page: params[:page]), :method => :post, :class => "btn btn-success", remote: true %>
<% end %>

app/views/topics/_tr.html.erb
<tr id="topic-<%= topic.id %>">
  <td >#</td>
    <td><% topic.categories.each do |catgory| %>
      <button> <%= catgory.title %> </button>
      <% end %>
    </td>
    <td><%= link_to topic.name,topic_path(topic) %></td>
    <td><%= topic.viewcount %></td>
    <td><%= topic.user.email %></td>
    <td><%= topic.created_at  %></td>
    <td><%= topic.comments_count %></td>
    <td><%= topic.last_time %></td>
    <td id="topic-like-count-<%= topic.id %>"><%= topic.liked_users.count %></td>

    <td id="topic-like-<%= topic.id %>">
      <%= render partial: "like", locals: {topic: topic} %>
    </td>
    <td id="topic-like-btn-<%= topic.id %>">
      <%= render partial: "likebutton", locals: {topic: topic} %>
    </td>
    <% if current_user %>
      <% if  current_user == topic.user  || current_user.admin?  %>
      <td><%= link_to("Edit",edit_topic_path(topic), class: "btn btn-info") %></td>
      <td><%= link_to("Delete",topic_path(topic),method: :delete, data:{confirm: "Are U sure??"}, class: "btn btn-warning",remote: true) %></td>
      <!-- <td><%= link_to("Delete",topic_path(topic),method: :delete, data:{confirm: "Are U sure??"}, class: "btn btn-warning") %></td> -->
    <% end %>
  <% end %>

</tr>

app/views/topics/about.html.erb
<div class="container">
  <div class="text-center">
      <h1 >本站介紹</h1><br>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption text-center">
          <h3>全站使用人數：</h3>
          <br>
          <h3><%= User.count %> 人</h3>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption text-center">
          <h3>全站主題數：</h3>
          <br>
          <h3><%=Topic.count %>篇</h3>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption text-center">
          <h3>全站回覆數：</h3>
          <br>
          <h3><%= Comment.count %>則</h3>
        </div>
      </div>
    </div>
</div>

app/views/topics/destroy.js.erb
$(" #topic-<%= @topic.id %>").remove();


$("#topics-count").text(<%= Topic.count %>);

app/views/topics/edit.html.erb
<%= simple_form_for @topic do |f| %>
  <div class="form-group">
    <%= f.input :name , input_html:{class: "form-control"} %>
    <%= f.association :categories,   as: :check_boxes %>
    <% if @photo.image.present? %>
      <%= image_tag(@photo.image.thumb.url) %>
    <% else %>
      <%= f.simple_fields_for :photo do |c| %>
        <%= c.input "上傳照片", as: :file %>
      <% end %>
    <% end %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting....."} %>
<% end %>
<div class="text-center">
  <%= link_to("回上一頁", topics_path, class:'btn btn-primary') %>
</div>

app/views/topics/index.html.erb
<div class="row text-center">
<h3>選擇分類：</h3>
<%= simple_form_for topics_path, method: :get do %>
<%= select_tag "category", options_from_collection_for_select(Category.all, "title", "title", params[:category]), onchange: 'this.form.submit()', prompt: "請選擇" %>
 <% end %> <br><br>

<%= link_to("文章名稱排序",topics_path(new: :name),class: 'btn btn-success') %>
<%= link_to("文章ＩＤ排序", topics_path(new: :id), class: "btn btn-success") %>
<%= link_to("(最新文章)排序",topics_path(new: :time),class: 'btn btn-success') %>
<%= link_to("最後回覆時間排序",topics_path(last: :time),class: 'btn btn-success') %>
<%= link_to("最多回覆數排序",topics_path(max: :count), class: "btn btn-info") %>
<%= link_to("分類管理",categories_path,class: "btn btn-info") %>
<%= link_to("Create",new_topic_path,class:"btn btn-warning ") %>
<br><br><br>
<h3>數量：<span id='topics-count'> <%= Topic.count %> </span></h3>
</div>
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>分類</th>
        <th>Topic名稱</th>
        <th><%= link_to("Topic瀏覽人數", topics_path(view: :count), class: "btn btn-info ") %></th>
        <th>Creator</th>
        <th>Topic發表時間</th>
        <th>Comment數量</th>
        <th>最後comment時間</th>
        <th>按讚人數</th>
        <th>Who likes</th>
        <th>Like/Unlike</th>

      </tr>
    </thead>
    <tbody>
      <% @topics.each do |topic| %>
        <%= render partial: "tr", locals: {topic: topic} %>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= will_paginate @topics %>
  </div>
</div>


<!--


<div class="row">
  <% @topics.each do |topic| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="text-left">
        <h4>最後回覆時間：<%= topic.last_time %></h4>
      </div>
      <div class="text-right">
        <h4>回覆數：<%= topic.comments.count %></h4>
      </div>
      <p>分類：
        <% topic.categories.each do |category| %>
        <button> <%= category.title %> </button>
        <% end %>
      </p>
      <div class="caption text-center">
        <h3><%= link_to topic.name,topic_path(topic) %></h3>
        <br>
        <p>
        <%= link_to("Show",topic_path(topic), class: "btn btn-primary") %>
        <%= link_to("Edit",edit_topic_path(topic), class: "btn btn-info") %>
        <%= link_to("Delete",topic_path(topic),method: :delete, data:{confirm: "Are U sure??"}, class: "btn btn-warning") %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div> -->

app/views/topics/like.js.erb
str = "<%=j render partial: "like", locals: {topic: @topic} %>"
btn = "<%=j render partial: "likebutton", locals: {topic: @topic} %>"


$("#topic-like-<%= @topic.id %>").html(str);
$("#topic-like-btn-<%= @topic.id %>").html(btn);

$("#topic-like-count-<%= @topic.id %>").text(<%= @topic.liked_users.count %>);

app/views/topics/show.html.erb
<div class="container">
  <% if current_user && !current_user.is_store_of?(@topic) %>
      <%= link_to("收藏本篇文章", store_topic_path(@topic), method: :post, class: "btn btn-success pull-right") %>
  <% else %>
      <%= link_to("移除收藏文章", unstore_topic_path(@topic), method: :post, class: "btn btn-warning pull-right") %>
  <% end %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>名稱</th>
        <th>Photo</th>
        <th>Creator</th>
        <th>瀏覽人數</th>
        <th>誰收藏</th>
        <th>參與討論人員</th>
      </tr>
    </thead>
    <tbody>
          <tr>
            <td><%= @topic.name %></td>
            <td><% if @topic.photo.present? %>
              <%= image_tag(@topic.photo.image.medium.url,class:"thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/100x100&text=No Pic", class:"thumbnail") %>
            <% end %>
            </td>
            <td><%= @topic.user.email %></td>
            <td><%=  @topic.viewcount %></td>
            <td>
              <% if @topic.stored_users.present? %>
                <% @topic.stored_users.each do |user| %>
                    <%= user.display_name %>
                <% end %>
              <% end %>
            </td>
            <td>
              <% @comment_member.each do |member| %>
                <%= User.find(member).display_name %> <br>  
              <% end %>
            </td>

          </tr>
    </tbody>
  </table>
</div>
<div class="container" >
  <h3 class="text-center">Comment </h3>
  <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>回覆內容</th>
        <th>Comment's Photo</th>
        <th>Comment's creator</th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.content %></td>
          <td>
          <% if comment.photo.present? %>
            <%= image_tag(comment.photo.image.thumb.url, class: "thumbnail") %>
          <% else %>
            <%= image_tag("http://placehold.it/25x25&text=No Pic", class:"thumbnail") %>
          <% end %>
          </td>
          <td>
            <% if comment.user.present? %>
              <%= comment.user.email %>
            <% end %>
          </td>
          <td>
            <% if current_user && current_user == comment.user %>
              <%= link_to("Edit",topic_path(comment_id: comment),class:"btn btn-info") %>
              <%= link_to("Delete",del_comment_topic_path(comment_id: comment),method: :post, class: "btn btn-warning") %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= simple_form_for @comment, url: comment_topic_path(comment_id: @comment),method: :post do |f| %>
    <div class="form-group">
      <%= f.input :content , placeholder: '回覆評論',input_html:{class: "form-control"} %>
    <% if @photo.image.present? %>
      <%= image_tag(@photo.image.thumb.url, class: "thumbnail") %>
    <% end %>
      <%= f.simple_fields_for :photo do |c| %>
        <%= c.input :image,label: '回覆上傳照片', as: :file %>
      <% end %>

    </div>
    <%= f.submit "發表評論", class: "btn btn-primary", data: {disable_with: "Submitting....."} %>
  <% end %>


</div>

<div class="text-center">
  <%= link_to "回上一頁",topics_path, class: "btn btn-primary" %>
</div>