config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  scope path:'/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
  resources :topics
  end

    root "topics#index"
  get '/test',to: "topics#test"

  namespace :admin do
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :users do
    collection do
      get :profile
      put :edit_profile
      get :post_topics
      get :post_comments
      get :like_topics
      get :stored_topics

    end
  end

  resources :categories

  resources :topics do
    collection do
      get :about
      get :last_time
      get :comment_count

    end

    member do
      post :like
      post :unlike
      post :comment
      post :del_comment
      post :store
      post :unstore

    end

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :groups
  has_many :topics, dependent: :destroy
  has_one :profile
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_topics, through: :likes, source: :topic
  has_many :photos
  has_many :store_topicships
  has_many :store_topics, through: :store_topicships, source: :topic

  def display_name
    email.split("@").first
  end

  def store!(topic)
    store_topics << topic
  end

  def unstore!(topic)
    store_topics.delete(topic)
  end

  def is_store_of?(topic)
    store_topics.include?(topic)
  end

  def admin?
    is_admin
  end

  def to_admin
    self.update_columns(is_admin: true)
  end

  def to_normal
    self.update_columns(is_admin: false)
  end

  def self.from_omniauth(auth)
   # Case 1: Find existing user by facebook uid
   user = User.find_by_fb_uid( auth.uid )
   if user
    #  byebug
      user.fb_token = auth.credentials.token
      #user.fb_raw_data = auth
      user.save!
     return user
   end

   # Case 2: Find existing user by email
   existing_user = User.find_by_email( auth.info.email )
   if existing_user
     existing_user.fb_uid = auth.uid
     existing_user.fb_token = auth.credentials.token
     #existing_user.fb_raw_data = auth
     existing_user.save!
     return existing_user
   end

   # Case 3: Create new password
   user = User.new
   user.fb_uid = auth.uid
   user.fb_token = auth.credentials.token
   user.email = auth.info.email
   user.password = Devise.friendly_token[0,20]
   #user.fb_raw_data = auth
   user.save!
   return user
 end

  # def self.from_omniauth(auth)
  #
  #   #Rails.logger.info auth.inspect
  #   # Rails.logger.info "========="  #這是如果有錯的話可以用來檢查
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #
  #       user.email = auth.info.email
  #
  #       user.password = Devise.friendly_token[0,20]
  #       user.name = auth.info.name
  #
  #       user.image = auth.info.image
  #   end
  #
  # end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :admin_required
  def index
    @users = User.all
    
  end

  def to_admin
    @user = User.find(params[:id])
    @user.to_admin

    redirect_to admin_users_path
  end

  def to_normal
    @user = User.find(params[:id])
    @user.to_normal

    redirect_to admin_users_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
          sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
          set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
          session["devise.facebook_data"] = request.env["omniauth.auth"]
          redirect_to new_user_registration_url
      end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "admin"
  def profile
    if current_user.profile.present?
      @profile = current_user.profile
    else
      @profile = Profile.new
    end
    # @new_profile = current_user.build_profile()
    # byebug
  end

  def edit_profile

      @profile = current_user.build_profile(content_params)
      @profile.save

    redirect_to profile_users_path
    # byebug
    # @profie.save

  end

  def post_topics
    @topics = current_user.topics
  end

  def post_comments
    @comments = current_user.comments
  end

  def like_topics
    @topics = current_user.liked_topics
  end

  def stored_topics
    @topics = current_user.store_topics
  end

  

  private

  def content_params
    params.require(:profile).permit(:content)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/ad.html.erb
<table class="table table-hover">
  <h3 class="text-center">Admin 管理後台</h3>
  <thead>
    <tr>
      <th> 使用者列表</th>
      <th>  Email</th>
      <th> Edit</th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to("Edit", edit_user_registration_path) %></td>
    </tr>
    <% end %>

  </table>
</div>

app/views/users/admin.html.erb
<table class="table table-hover">
  <h3 class="text-center">Admin 管理後台</h3>
  <thead>
    <tr>
      <th> 使用者列表</th>
      <th>  Email</th>
      <th> Edit</th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to("Edit", edit_user_registration_path) %></td>
    </tr>
    <% end %>

  </table>
</div>

app/views/users/like_topics.html.erb
<div class="row">
  <% @topics.each do |topic| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <h4>文章名稱</h4>
      <div class="caption text-center">
        <h3><%= topic.name %></h3>
        <br>
        <p>
        <%= link_to("Show",topic_path(topic), class: "btn btn-primary") %>
        <!-- <%= link_to("Edit",edit_topic_path(topic), class: "btn btn-info") %>
        <%= link_to("Delete",topic_path(topic),method: :delete, data:{confirm: "Are U sure??"}, class: "btn btn-warning") %> -->
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/post_comments.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Comment名稱</th>
        </tr>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
            <tr>
              <td><%= link_to comment.content, topic_path(comment.topic_id) %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/post_topics.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>文章名稱</th>
        </tr>
      </thead>
      <tbody>
        <% @topics.each do |topic| %>
            <tr>
              <td><%= link_to topic.name, topic_path(topic) %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/profile.html.erb
<div class="text-center">
  <h1>個人簡介</h1><br>
  <div class="table table-bordered">
    <% if current_user.profile.present? %>
      <p><%= @profile.content  %></p>
    <% end %>
  </div>
<div class="table">
  <%= form_for @profile, url: edit_profile_users_path , method: :put do |f| %>
  <div class="form-group">
    <%= f.label "更新個人檔案" %>
    <%= f.text_field :content, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "更新", :class => "btn btn-primary" %>
  </div>
  <% end %>
</div>

</div>

app/views/users/stored_topics.html.erb
<div class="row">
  <% @topics.each do |topic| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="text-right">
        <h4>瀏覽人數：<%= topic.viewcount %></h4>
      </div>
      <div class="caption text-center">
        <h4>文章名稱：</h4>
        <h3><%= link_to(topic.name, topic_path(topic)) %></h3>
        <br>
      </div>
      <div class= "btn btn-warning pull-right">
      <%= link_to("取消收藏",unstore_topic_path(topic,topic: topic),method: :post) %>
      </div>
      <br><br>
    </div>
  </div>
  <% end %>
</div>