config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  scope path:'/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
  resources :topics
  end

    root "topics#index"
  get '/test',to: "topics#test"

  namespace :admin do
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :users do
    collection do
      get :profile
      put :edit_profile
      get :post_topics
      get :post_comments
      get :like_topics
      get :stored_topics

    end
  end

  resources :categories

  resources :topics do
    collection do
      get :about
      get :last_time
      get :comment_count

    end

    member do
      post :like
      post :unlike
      post :comment
      post :del_comment
      post :store
      post :unstore

    end

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topic_categoryships
  has_many :members, through: :topic_categoryships, source: :topic
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :topic, counter_cache: :comments_count
  belongs_to :user
  has_one :photo
  accepts_nested_attributes_for :photo
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :topics
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # belongs_to :user
  belongs_to :topic
  # belongs_to :comment
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/store_topicship.rb
class StoreTopicship < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :topic_categoryships
  has_many :categories, through: :topic_categoryships
  has_one :photo, dependent: :destroy
  accepts_nested_attributes_for :photo
  has_many :store_topicships
  has_many :stored_users, through: :store_topicships, source: :user
  # has_one :topicphoto
  # accepts_nested_attributes_for :topicphoto

  def find_like(user)
    Like.where(topic_id: self.id, user_id: user.id).first
    # Like.where(topic_id: id, user_id: user.id) #也可以

  end

  def is_like_by(user)
    find_like(user).present?
  end
end

app/models/topic_categoryship.rb
class TopicCategoryship < ActiveRecord::Base
  belongs_to :topic
  belongs_to :category
end

app/models/topicphoto.rb
class Topicphoto < ActiveRecord::Base
  belongs_to :topic
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :groups
  has_many :topics, dependent: :destroy
  has_one :profile
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_topics, through: :likes, source: :topic
  has_many :photos
  has_many :store_topicships
  has_many :store_topics, through: :store_topicships, source: :topic

  def display_name
    email.split("@").first
  end

  def store!(topic)
    store_topics << topic
  end

  def unstore!(topic)
    store_topics.delete(topic)
  end

  def is_store_of?(topic)
    store_topics.include?(topic)
  end

  def admin?
    is_admin
  end

  def to_admin
    self.update_columns(is_admin: true)
  end

  def to_normal
    self.update_columns(is_admin: false)
  end

  def self.from_omniauth(auth)
   # Case 1: Find existing user by facebook uid
   user = User.find_by_fb_uid( auth.uid )
   if user
    #  byebug
      user.fb_token = auth.credentials.token
      #user.fb_raw_data = auth
      user.save!
     return user
   end

   # Case 2: Find existing user by email
   existing_user = User.find_by_email( auth.info.email )
   if existing_user
     existing_user.fb_uid = auth.uid
     existing_user.fb_token = auth.credentials.token
     #existing_user.fb_raw_data = auth
     existing_user.save!
     return existing_user
   end

   # Case 3: Create new password
   user = User.new
   user.fb_uid = auth.uid
   user.fb_token = auth.credentials.token
   user.email = auth.info.email
   user.password = Devise.friendly_token[0,20]
   #user.fb_raw_data = auth
   user.save!
   return user
 end

  # def self.from_omniauth(auth)
  #
  #   #Rails.logger.info auth.inspect
  #   # Rails.logger.info "========="  #這是如果有錯的話可以用來檢查
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #
  #       user.email = auth.info.email
  #
  #       user.password = Devise.friendly_token[0,20]
  #       user.name = auth.info.name
  #
  #       user.image = auth.info.image
  #   end
  #
  # end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key,value| %>
    <div class="alert alert-dismissible alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container style="margin-top: 100px;"">
  <p class="text-center">Copyright ©2017  AC_camp
  <br>Design by
  <a href="#">LuPochia</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand"> 技術論壇 AC</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("註冊", new_user_registration_path) %></li>
          <li><%= link_to("登入", new_user_session_path) %></li>
        <% else %>
        <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.name %>
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to("About",about_topics_path) %>
                        <%= link_to("帳號設定", edit_user_registration_path) %>
                        <%= link_to("個人資訊後台", profile_users_path) %>
                        <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
                      </li>
                    </ul>
                  </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>個人資訊後台！</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <%= render "common/flashes" %>

    <div class="row">
        <div class="col-md-2">
            <ul class="nav nav-pills nav-stacked" style"max-width: 300px">
              <li><%= link_to("個人簡介",profile_users_path) %>
              </li>
              <li>  <%= link_to("所有張貼文章", post_topics_users_path) %>
              </li>
              <li>  <%= link_to("所有張貼回覆", post_comments_users_path) %></li>
              <li><%= link_to("按讚文章", like_topics_users_path) %></li>
              <li><%= link_to("收藏文章",stored_topics_users_path) %></li>
              <li><%= link_to("Admin後台",admin_users_path) %></li>
              <li>
                <%= link_to("返回Topic", topics_path) %>
              </li>
            </ul>
        </div>
        <div class="col-md-10">
            <%= yield %>
        </div>
    </div>
  </div>
  <%= render "common/footer" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <%= render "common/flashes" %>
    <%= yield %>
  </div>
  <%= render "common/footer" %>

</body>
</html>